Resources:
  ApiGatewayRestReverseProxyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ${opt:stage, 'poc'}-reverse-proxy-example
      Description: 'Example Reverse Proxy API'
      EndpointConfiguration:
        Types:
          - REGIONAL
