Resources:
  ResourceSage:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: ApiGatewayRestReverseProxyApi
      ParentId: !GetAtt ApiGatewayRestReverseProxyApi.RootResourceId
      PathPart: 'sage'

  ResourceSageProxy:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: ApiGatewayRestReverseProxyApi
      ParentId:
        Ref: ResourceSage
      PathPart: '{proxy+}'

  MethodSageAny:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: ResourceSageProxy
      RestApiId:
        Ref: ApiGatewayRestReverseProxyApi
      HttpMethod: ANY
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        CacheKeyParameters:
          - 'method.request.path.proxy'
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY
        Uri: !Join ['', ['${self:custom.config.sageUrl}', '/sage/v1', '/{proxy}']]

